# Generated by Django 5.1.3 on 2024-11-17 00:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('Atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='newItem.base')),
                ('marca_carro', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Marcas',
                'ordering': ('marca_carro',),
            },
            bases=('newItem.base',),
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='newItem.base')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('chassi', models.CharField(max_length=255, unique=True, verbose_name='Chassi')),
                ('cor', models.CharField(max_length=10, verbose_name='Cor')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_combustivel', models.CharField(choices=[('Gasolina', 'Gasolina'), ('Diesel', 'Diesel'), ('Eletrico', 'Elétrico'), ('Hibrido', 'Híbrido')], default='GASOLINA', max_length=20)),
                ('ano', models.IntegerField()),
                ('imagem', models.ImageField(upload_to='media')),
                ('marca_carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='newItem.marca')),
            ],
            bases=('newItem.base',),
        ),
    ]
