# Generated by Django 5.1.3 on 2024-11-26 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newItem', '0002_alter_carro_cor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='base',
            old_name='Atualizado_em',
            new_name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='base',
            name='criado_por',
        ),
        migrations.AddField(
            model_name='carro',
            name='criado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
